// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250617225110_ProjectCreated")]
    partial class ProjectCreated : Migration // Changed base class to Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Migration logic for applying changes
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Migration logic for reverting changes
        }
    }
}
